server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3307/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root          # ← change to your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# Product Service
product:
  service:
    base-url: http://localhost:8081

logging:
  level:
    com.example.order: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info